const express = require('express');
const cors = require('cors');
const favicon = require('serve-favicon');
const path = require('path');
const bodyParser = require('body-parser');
const config = require('./config');
const usuarioRoutes = require('./routes/usuarioRoute');
const obraRoutes = require('./routes/obraRoute');
const categoriasRoutes = require('./routes/categoriaRoute');
const tipoobrasRoutes = require('./routes/tipoobraRoute');
const paisesRoutes = require('./routes/paisRoute');
const temporadaRoutes = require('./routes/temporadaRoute');
const episodioRoutes = require('./routes/episodioRoute');
const avaliacaoRoutes = require('./routes/avaliacaoRoute');
const funcaoRoutes = require('./routes/funcaoRoute');
const profissionalRoutes = require('./routes/profissionalRoute');
const criticoRoutes = require('./routes/criticoRoute');
const moderadorRoutes = require('./routes/moderadorRoute');
const participacaoRoutes = require('./routes/participacaoRoute');
const organizacaoRoutes = require('./routes/organizacaoRoute');
const listausuarioRoutes = require('./routes/listausuarioRoute');
const obraCategoriaRoutes = require('./routes/obracategoriaRoute');
const obrapaisRoutes = require('./routes/obrapaisRoute');
const obralistausuarioRoutes = require('./routes/obralistausuarioRoute');
const participacaoObraRoutes = require('./routes/participacaoObraRoute');
const participacaoOrganizacaoRoutes = require('./routes/participacaoOrganizacaoRoute');
const participacaoFuncaoRoutes = require('./routes/participacaoFuncaoRoute');
const participacaoProfissionalRoutes = require('./routes/participacaoProfissionalRoute');
const listausuarioUsuarioRoutes = require('./routes/listausuarioUsuarioRoute');
const avaliacaoEpisodioRoutes = require('./routes/avaliacaoEpisodioRoute');
const avaliacaoObraRoutes = require('./routes/avaliacaoObraRoute');
const avaliacaoUsuarioRoutes = require('./routes/avaliacaoUsuarioRoute');
const temporadaObraRoutes = require('./routes/temporadaObraRoute');
const episodioTemporadaRoutes = require('./routes/episodioTemporadaRoute');
const obraTipoobraRoutes = require('./routes/obraTipoobraRoute');
const obracategoriaObraRoutes = require('./routes/obracategoriaObraRoute');
const obracategoriaCategoriaRoutes = require('./routes/obracategoriaCategoriaRoute');
const obrapaisObraRoutes = require('./routes/obrapaisObraRoute');
const obrapaisPaisRoutes = require('./routes/obrapaisPaisRoute');
const obralistausuarioObraRoutes = require('./routes/obralistausuarioObraRoute');
const obralistausuarioListaRoutes = require('./routes/obralistausuarioListaRoute');
const loginRoutes = require('./routes/loginRoute');
const filmeRoutes = require('./routes/filmeRoute');
const serieRoutes = require('./routes/serieRoute');
const animeRoutes = require('./routes/animeRoute');
const documentarioRoutes = require('./routes/documentarioRoute');
const curtaRoutes = require('./routes/curtaRoute');
const avaliacaoObraUsuarioRoutes = require('./routes/avaliacaoObraUsuarioRoute');
const avaliacaoEpisodioUsuarioRoutes = require('./routes/avaliacaoEpisodioUsuarioRoute');
const buscarObraRoutes = require('./routes/buscarobraRoute');

// Configuração do Express
const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

// Mostrando HTML estático na raiz
app.get('/', (req, res) => res.sendFile(path.join(__dirname, 'public', 'index.html')));
app.use(favicon(path.join(__dirname, 'public', 'img', 'favicon.ico')));
app.use(express.static(path.join(__dirname, 'public')));

// Rotas
app.use('/usuarios', usuarioRoutes);
app.use('/obras', obraRoutes);
app.use('/categorias', categoriasRoutes);
app.use('/tipoobras', tipoobrasRoutes);
app.use('/paises', paisesRoutes);
app.use('/temporadas', temporadaRoutes);
app.use('/episodios', episodioRoutes);
app.use('/avaliacoes', avaliacaoRoutes);
app.use('/funcoes', funcaoRoutes);
app.use('/profissionais', profissionalRoutes);
app.use('/criticos', criticoRoutes);
app.use('/moderadores', moderadorRoutes);
app.use('/participacoes', participacaoRoutes);
app.use('/organizacoes', organizacaoRoutes);
app.use('/listasusuario', listausuarioRoutes);
app.use('/obrascategorias', obraCategoriaRoutes);
app.use('/obraspaises', obrapaisRoutes);
app.use('/obraslistasusuario', obralistausuarioRoutes);
app.use('/participacoesobras', participacaoObraRoutes);
app.use('/participacoesorganizacao', participacaoOrganizacaoRoutes);
app.use('/participacoesfuncao', participacaoFuncaoRoutes);
app.use('/participacoesprofissional', participacaoProfissionalRoutes);
app.use('/listasusuariousuario', listausuarioUsuarioRoutes);
app.use('/avaliacoesepisodio', avaliacaoEpisodioRoutes);
app.use('/avaliacoesobra', avaliacaoObraRoutes);
app.use('/avaliacoesusuario', avaliacaoUsuarioRoutes);
app.use('/temporadasobra', temporadaObraRoutes);
app.use('/episodiostemporada', episodioTemporadaRoutes);
app.use('/obrastipoobra', obraTipoobraRoutes);
app.use('/obrascategoriasobra', obracategoriaObraRoutes);
app.use('/obrascategoriascategoria', obracategoriaCategoriaRoutes);
app.use('/obraspaisesobra', obrapaisObraRoutes);
app.use('/obraspaisespais', obrapaisPaisRoutes);
app.use('/obraslistasusuarioobra', obralistausuarioObraRoutes);
app.use('/obraslistasusuariolista', obralistausuarioListaRoutes);
app.use('/login', loginRoutes);
app.use('/filmes', filmeRoutes);
app.use('/series', serieRoutes);
app.use('/animes', animeRoutes);
app.use('/documentarios', documentarioRoutes);
app.use('/curtas', curtaRoutes);
app.use('/avaliacoesobrausuario', avaliacaoObraUsuarioRoutes);
app.use('/avaliacoesepisodiousuario', avaliacaoEpisodioUsuarioRoutes);
app.use('/buscarobra', buscarObraRoutes);

// Iniciando servidor
const port = config.port || 3000;
app.listen(port, () => {
  console.log('Servidor Rodando. URL Local: http://localhost:' + port);
});
