-- Updates gerados pelo tmdb_fetch_images.js
-- Execute este arquivo após as tabelas existirem para atualizar obraImgUrl
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/zdowK9GrOxK0YddhXuMPyxnTA02.jpg' WHERE obraTitulo = 'The Lighthouse';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/4DGPORlVIDIQvsuSDnM4uXKMjWS.jpg' WHERE obraTitulo = 'Parasite';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/9e3Dz7aCANy5aRUQF745IlNloJ1.jpg' WHERE obraTitulo = 'Inception';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/6ricSDD83BClJsFdGB6x7cM0MFQ.jpg' WHERE obraTitulo = 'Interstellar';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/4ezwRuc1iKlaWTi16qrr44Nzinr.jpg' WHERE obraTitulo = 'The Shape of Water';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/yabOguSrb8ffUXCkI6t8Rw7xtSh.jpg' WHERE obraTitulo = 'The Grand Budapest Hotel';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/AekOkoT88EhDHikUQXQcKri2q4B.jpg' WHERE obraTitulo = 'Moonlight';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/z693uKD7j3zcdX0zVMQPIA3cSZf.jpg' WHERE obraTitulo = 'Whiplash';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/AvMietG6xuobpSSdmVnKuTjv4bL.jpg' WHERE obraTitulo = 'La La Land';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/mtgqrSlT47VsmeMVanLTny7BknB.jpg' WHERE obraTitulo = 'Mad Max: Fury Road';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/oJagOzBu9Rdd9BrciseCm3U3MCU.jpg' WHERE obraTitulo = 'The Godfather';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/tptjnB2LDbuUWya9Cx5sQtv5hqb.jpg' WHERE obraTitulo = 'Pulp Fiction';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/lDqMDI3xpbB9UQRyeXfei0MXhqb.jpg' WHERE obraTitulo = 'The Matrix';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/3GPn2W2UdzUE1bp1KtCrYvXiZFt.jpg' WHERE obraTitulo = 'The Irishman';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/pLwarSuyUjw6vF0U6JhlHzAa1Gp.jpg' WHERE obraTitulo = 'Nomadland';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/jXbqfVHmvCikyTw2Lf5OhKyt9Ym.jpg' WHERE obraTitulo = 'The Social Network';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/wHNzfrfK8M4WIq3XDUqAFdKKY5Z.jpg' WHERE obraTitulo = 'Spotlight';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/7XygOiL1LoaLfAbKayGSY5BJQDl.jpg' WHERE obraTitulo = 'Get Out';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/ubXNpxL2ASSzY0f8Hxv08pOsV2L.jpg' WHERE obraTitulo = 'Black Panther';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/qtnAwzDapzOML4Q9p7lv2bk5gvz.jpg' WHERE obraTitulo = 'The Departed';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/yyDGhBY8RYXyXYADeFq1BDxpLkl.jpg' WHERE obraTitulo = 'Her';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/hRotKKijqV6YibxnhSOureF5efx.jpg' WHERE obraTitulo = 'The Revenant';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/fmngHGvRYC9wT3nEFOcVsXGp9pH.jpg' WHERE obraTitulo = 'A Separation';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/xRv3FbRpbaRm7xW4JGVZEXxmHTv.jpg' WHERE obraTitulo = 'Shoplifters';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/q6ngYthHXCvA2ZubO4FHTFNRrmc.jpg' WHERE obraTitulo = 'The Handmaiden';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/8NzeFPRCrolFXzJnVmuZ5jR6fEC.jpg' WHERE obraTitulo = 'The Farewell';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/rr1rlDZXOeLqtYMEC6xEunxqsD3.jpg' WHERE obraTitulo = 'Boyhood';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/9n0u3Ee7OUjgeyF5kIwahxkf4xm.jpg' WHERE obraTitulo = 'Birdman';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/rbPTCnxQgEsWdetEcPiaKstX7mp.jpg' WHERE obraTitulo = 'The Truman Show';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/qnf5Onsk236CdE5Lff93IX69gHf.jpg' WHERE obraTitulo = 'Call Me By Your Name';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/602vevIURmpDfzbnv5Ubi6wIkQm.jpg' WHERE obraTitulo = 'Drive';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/vLbmmqa3Ys03biY6kkzMEHdIGBD.jpg' WHERE obraTitulo = 'Oldboy';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/zqCyj7ZJSc3d0Yh04pJ6jMyhQKG.jpg' WHERE obraTitulo = 'City of God';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/81GtiOYId1thLy8ZT9aGrCptch4.jpg' WHERE obraTitulo = 'Amélie';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/esJTXTdj4JZDyP5LUI1Fq3kyNda.jpg' WHERE obraTitulo = 'The Wolf of Wall Street';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/zqbwK2ugTPauBQwzcNAM3PxVoww.jpg' WHERE obraTitulo = 'Eternal Sunshine of the Spotless Mind';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/7leBWM27Q0TUnvmhw6WnFNgGn4G.jpg' WHERE obraTitulo = 'Memento';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/jdlY8Bhcb4Qzfldr1JaexYBgyW3.jpg' WHERE obraTitulo = 'No Country for Old Men';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/8djpxDeWpINnGhjpFXQjnBe6zbx.jpg' WHERE obraTitulo = 'The Expanse';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/7EZcuL3GuiNvwn5RlKLaWazzekL.jpg' WHERE obraTitulo = 'Stranger Things';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/hGwm9Cj3CdbJIqQWNExQqiYmCd4.jpg' WHERE obraTitulo = 'Breaking Bad';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg' WHERE obraTitulo = 'Chernobyl';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/27vEYsRKa3eAniwmoccOoluEXQ1.jpg' WHERE obraTitulo = 'Fleabag';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/9IPVuAjodjc2FYluWnNvRdOPsCR.jpg' WHERE obraTitulo = 'Better Call Saul';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/ehUMAA3qDR5HNor9DB60g72KNQZ.jpg' WHERE obraTitulo = 'The Crown';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/fbKE87mojpIETWepSbD5Qt741fp.jpg' WHERE obraTitulo = 'Mindhunter';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg' WHERE obraTitulo = 'The Mandalorian';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/7yQyDCqSazrYTnmxdQLAZ8YDH87.jpg' WHERE obraTitulo = 'Dark';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/mPx9pxwXpUTz5TFAi267rQdbGuR.jpg' WHERE obraTitulo = 'Killing Eve';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/eJJvzADsstZAz4tmE5qa3jjPUkF.jpg' WHERE obraTitulo = 'The Handmaid''s Tale';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/7WTsnHkbA0FaG6R9twfFde0I9hl.jpg' WHERE obraTitulo = 'Sherlock';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/1fxr55V72a2gtqyn2b8pf6FslOf.jpg' WHERE obraTitulo = 'True Detective';
UPDATE Obra SET obraImgUrl = 'https://image.tmdb.org/t/p/w500/aCTL24B8ZuiI2osMwoUI5rqBXoF.jpg' WHERE obraTitulo = 'Black Mirror';
